target 'iosApp' do
  platform :ios, '15.0'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-4'
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-4'
  pod 'Factory', '1.3.5'
end
