name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 24
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-disabled: true
      - name: Ktfmt
        run: ./gradlew ktfmtCheck :build-logic:convention:ktfmtCheck
      - name: Detekt
        run: ./gradlew detektAll
      - name: Test
        run: ./gradlew testDebugUnitTest
      - name: Build
        run: ./gradlew assembleDebug
